### ISSUE TITLE
Several necessary commands for running long-hub for the first time?

### ISSUE THREAD

**Issue by AENSAX** [MoveToEx/long-hub#1]
Running the project for the first time also requires executing database file generation and migration commands  
recommend to add the **py management. py runserver** option before using it in the method：
```sh
$ py manage.py makemigrations
$ py manage.py migrate
```
: )

**Comment by AENSAX** [comment]
emmm,I have run like this,but....  
![](https://raw.githubusercontent.com/aurora-wangq/IMG/main/20230809020441.png)

**Comment by aurora-wangq** [comment]
> 嗯，我就这样跑了，但是.... ![](https://raw.githubusercontent.com/aurora-wangq/IMG/main/20230809020441.png)

I try to change my database,but.....the same issue

**Comment by AENSAX** [comment]
> emmm,I have run like this,but.... ![](https://raw.githubusercontent.com/aurora-wangq/IMG/main/20230809020441.png)
I even change my database,but..... the same issue

**Comment by AENSAX** [comment]
> > emmm,I have run like this,but.... ![](https://raw.githubusercontent.com/aurora-wangq/IMG/main/20230809020441.png)
> > I even change my database,but..... the same issue

then I tried to manually modify it,but more bugs append!this time the bug appear when I upload images.

**Comment by AENSAX** [comment]
用狗屎英语，写狗屎issue

**Comment by MoveToEx** [comment]
fixed
